### PR TITLE
Include LICENSE file in source distribution

### PR DESCRIPTION
**Pull request by JeffLIrion**

### CODE REVIEW

**Comment by JeffLIrion** [comment]
@fabaff will this change result in the LICENSE file being added to the source tarball?

**Comment by fabaff** [comment]
Yes, for the tarball which will be available at PyPI. But not the one on GitHub.

**Comment by JeffLIrion** [comment]
> Yes, for the tarball which will be available at PyPI. But not the one on GitHub.

How do I get the LICENSE file included in the tarball from GitHub?

**Comment by fabaff** [comment]
> How do I get the LICENSE file included in the tarball from GitHub?

The LICENSE file is already there as it's in the repo. The GitHub tarball includes everything that's in the repo when it's tagged.

**Comment by JeffLIrion** [comment]
```bash
wget https://github.com/JeffLIrion/adb_shell/archive/v0.1.3.tar.gz
tar -xf v0.1.3.tar.gz
ls adb_shell-0.1.3/
```

The LICENSE file is there, so I'm not sure what https://github.com/JeffLIrion/adb_shell/issues/84 is about. Am I missing something?

**Comment by fabaff** [comment]
It's missing the source tarball at PyPI. Seems that I was not clearly mentioning that in the first place.

https://files.pythonhosted.org/packages/ac/49/3ecbc0575d64689673ff063bfa090a620e2af5b53e8075120f895ded4406/adb_shell-0.1.3.tar.gz

**Comment by JeffLIrion** [comment]
> It's missing the source tarball at PyPI. Seems that I was not clearly mentioning that in the first place.
> 
> https://files.pythonhosted.org/packages/ac/49/3ecbc0575d64689673ff063bfa090a620e2af5b53e8075120f895ded4406/adb_shell-0.1.3.tar.gz

I was confused because on one computer when I would create a release, it would include the LICENSE file with or without the MANIFEST.in file, but on another computer it would not include the LICENSE file if the MANIFEST.in file was not present.  I upgraded the `setuptools` package on that computer and now it includes the LICENSE file either way.  

Thanks for pointing out to me what the issue was!

**Pull request merged**
